import React, { useState, useEffect } from 'react';
import { ChevronLeft, ChevronRight, Brain, Target, TrendingUp, Award, Zap, BookOpen } from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Learning',
    description: 'Personalized course content generated by advanced AI to match your learning style and goals.',
    gradient: 'from-purple-500 to-pink-500'
  },
  {
    icon: Target,
    title: 'Goal-Oriented Paths',
    description: 'Set your objectives and let Cerebro create a customized learning journey tailored to your needs.',
    gradient: 'from-blue-500 to-cyan-500'
  },
  {
    icon: TrendingUp,
    title: 'Progress Tracking',
    description: 'Monitor your learning progress with detailed analytics and insights to stay motivated.',
    gradient: 'from-green-500 to-emerald-500'
  },
  {
    icon: Award,
    title: 'Interactive Quizzes',
    description: 'Test your knowledge with AI-generated quizzes that adapt to your understanding level.',
    gradient: 'from-orange-500 to-red-500'
  },
  {
    icon: Zap,
    title: 'Instant Generation',
    description: 'Create comprehensive courses in seconds with our powerful AI engine.',
    gradient: 'from-yellow-500 to-orange-500'
  },
  {
    icon: BookOpen,
    title: 'Structured Content',
    description: 'Well-organized modules and lessons that build upon each other for effective learning.',
    gradient: 'from-indigo-500 to-purple-500'
  }
];

const FeaturesCarousel = () => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isPaused, setIsPaused] = useState(false);

  useEffect(() => {
    if (isPaused) return;

    const interval = setInterval(() => {
      setCurrentIndex((prev) => (prev + 1) % features.length);
    }, 4000);

    return () => clearInterval(interval);
  }, [isPaused]);

  const goToSlide = (index) => {
    setCurrentIndex(index);
  };

  const goToPrevious = () => {
    setCurrentIndex((prev) => (prev - 1 + features.length) % features.length);
  };

  const goToNext = () => {
    setCurrentIndex((prev) => (prev + 1) % features.length);
  };

  const currentFeature = features[currentIndex];
  const Icon = currentFeature.icon;

  return (
    <div 
      className="relative overflow-hidden rounded-2xl glass-card p-8 md:p-12"
      onMouseEnter={() => setIsPaused(true)}
      onMouseLeave={() => setIsPaused(false)}
    >
      {/* Content */}
      <div className="flex flex-col md:flex-row items-center gap-8">
        {/* Icon */}
        <div className={`w-20 h-20 md:w-24 md:h-24 rounded-2xl bg-gradient-to-br ${currentFeature.gradient} flex items-center justify-center flex-shrink-0 animate-in zoom-in duration-300`}>
          <Icon className="w-10 h-10 md:w-12 h-12 text-white" />
        </div>

        {/* Text */}
        <div className="flex-1 text-center md:text-left">
          <h3 className="text-2xl md:text-3xl font-bold mb-3 animate-in slide-in-from-right duration-300">
            {currentFeature.title}
          </h3>
          <p className="text-muted-foreground text-lg animate-in slide-in-from-right duration-300 delay-75">
            {currentFeature.description}
          </p>
        </div>
      </div>

      {/* Navigation Arrows */}
      <div className="absolute top-1/2 -translate-y-1/2 left-4 right-4 flex justify-between pointer-events-none">
        <button
          onClick={goToPrevious}
          className="w-10 h-10 rounded-full bg-background/80 border border-border flex items-center justify-center hover:bg-accent transition-colors pointer-events-auto"
          aria-label="Previous feature"
        >
          <ChevronLeft className="w-5 h-5" />
        </button>
        <button
          onClick={goToNext}
          className="w-10 h-10 rounded-full bg-background/80 border border-border flex items-center justify-center hover:bg-accent transition-colors pointer-events-auto"
          aria-label="Next feature"
        >
          <ChevronRight className="w-5 h-5" />
        </button>
      </div>

      {/* Dots Indicator */}
      <div className="flex items-center justify-center gap-2 mt-8">
        {features.map((_, index) => (
          <button
            key={index}
            onClick={() => goToSlide(index)}
            className={`h-2 rounded-full transition-all ${
              index === currentIndex 
                ? 'w-8 bg-primary' 
                : 'w-2 bg-muted-foreground/30 hover:bg-muted-foreground/50'
            }`}
            aria-label={`Go to feature ${index + 1}`}
          />
        ))}
      </div>
    </div>
  );
};

export default FeaturesCarousel;
